### ISSUE TITLE
UI: add Publish Draft option

### ISSUE THREAD

**Issue by marcinbodnar** [NearSocial/viewer#147]
With the Draft version available, we can add an option that will be available only for the Draft version of the widget, which will allow publishing the draft version as a main version with one button.

It will:
 - copy the draft version to the main widget
 - publish the main widget
 - remove the draft version.

**Comment by mpeterdev** [comment]
closed in alpha.near.org viewer by above mentioned PR. If this is desired on Social we can have a more generic effort to port editor improvements
