### ISSUE TITLE
UI: add autosave checkbox to Save in Local Storage option

### ISSUE THREAD

**Issue by marcinbodnar** [NearSocial/viewer#148]
When the "Save in Local Storage" option will be ready, we can easily extend it with "autosave" option - it can have a form of checkbox near the "Save in Local Storage" button. When the checkbox is checked, every change to the code will be automatically saved in local storage.

**Comment by evgenykuzyakov** [comment]
It already autosaves it to local storage. Do you want the local version of the code be accessible outside of the editor?

**Comment by marcinbodnar** [comment]
@evgenykuzyakov the initial idea was to disable the default autosave and give the user an option to save it manually (locally) or enable/disable autosave. But we resign of it.
