### ISSUE TITLE
Flex containers brake with long list of data

### ISSUE THREAD

**Issue by petarvujovic98** [NearSocial/viewer#157]
I have a common wrapper around a list that changes based on a tab selector.
The list fetches data from a smart contract and creates cards to display the data points.
When the data list is long, flex components go way off screen.
Here is how it looks on a small data set:
![Screenshot_20230301_012308](https://user-images.githubusercontent.com/36507050/222138297-abb746e2-b217-4e02-8afd-7931cf1086aa.png)
And here is what it looks like with a larger data set:
![Screenshot_20230301_012351](https://user-images.githubusercontent.com/36507050/222138504-0a4071bb-e28c-41aa-8870-59092489f03d.png)
![Screenshot_20230301_012408](https://user-images.githubusercontent.com/36507050/222138510-54c1e0e4-e5c8-40fe-b308-cf2d102de760.png)

The link to the app is [contribut3.near.social](https://contribut3.near.social).

P.S. The left sidebar should be sticky but doesn't appear to actually behave like a sticky element.

**Comment by evgenykuzyakov** [comment]
Looks like CSS issue? Can you put a `maxWidth: 100%` somewhere to prevent it?

**Comment by petarvujovic98** [comment]
@evgenykuzyakov I've reorganized the description area and tags list lengths so that the don't push out the rest of the card's items and thus make the rest of the UI pushed out as well. Sorry to bother about this.
