### ISSUE TITLE
Feature Request: Consider using emotion

### ISSUE THREAD

**Issue by agileurbanite** [NearSocial/viewer#32]
Feature Request: Consider using emotion

Emotion is a css in js library to add styling to components either in react or vanilla

**Comment by agileurbanite** [comment]
If we end up using Chakra for #33 then #32 can auto-close as chakra uses emotion under the hood as a dep.

**Comment by agileurbanite** [comment]
This requires a version bump of react from 16 to 18 #35

**Comment by mpeterdev** [comment]
I think this is safe to close since we have styled-components
