### ISSUE TITLE
Feature Request: Add component library for faster and consistent widget development

### ISSUE THREAD

**Issue by agileurbanite** [NearSocial/viewer#33]
A component system like https://chakra-ui.com/docs/components can enable faster widget development that is consistent and also extensible while introducing concepts like accessibility out of the box.

**Comment by evgenykuzyakov** [comment]
Is chakra compatible with Bootstrap? If not, it will be a breaking change and requires a good reason to implement

**Comment by mpeterdev** [comment]
Pagoda is working on a design system which will handle this use case. Closing for now, but can be reopened for discussion if desired
